### PR TITLE
Made appropriate change for fixing variable error report

### PR DESCRIPTION
**Pull request by djinn**

### CODE REVIEW

**Comment by vanng822** [comment]
Great, I have some time so I was thinking fixing the tests but you are already there. Sorry for not waiting for your answer.

There were 2 files that need to fix. I guess you have to time to help with the second file as well

**Comment by vanng822** [comment]
I was on the way to introduce github.com/stretchr/testify/assert Regexp
github.com/stretchr/testify/assert provide really good assertions functionalities :-)

**Comment by djinn** [comment]
Strangely these errors are not showing up on my setup. I use 1.5.1

**Comment by djinn** [comment]
Good to go now. Assert will be a great idea.

**Comment by vanng822** [comment]
not my either, it must have to do with the dns resolver settings in travis.

Thank for helping, I merge

Yeah, this is my first golang project for learning so there is a lot of thing we can improve

**Pull request merged**
