### PR TITLE
Reuse the http connections in connection pool instead of initiating client connection for each request

### PR DESCRIPTION
**Pull request by djinn**

### CODE REVIEW

**Comment by vanng822** [comment]
Thank for the PR @djinn This is great, one off the thing on my list. Would this change enough or should we do something more?

Let's see what has been changed in dev that make the tests failed. Maybe we just run for 1.4 and 1.5 instead of tip?

**Comment by djinn** [comment]
Let me run the test case myself to check. Ideally it should reduce number
of solr back end connections

**Comment by djinn** [comment]
Just checked the travis output. It seems that the error text has changed between 1.4 and tip. Otherwise this is good to go.

**Comment by vanng822** [comment]
Yes @djinn I saw that and have also run on v1.5 so I suggest that we only run for stable versions of go, let's run only for 1.4 and 1.5. Do you want to make this change in .travis.yml? Would be nice if we do this first before merging

**Comment by djinn** [comment]
Sure.


On Mon, Dec 28, 2015 at 4:54 PM, Nguyen Van Nhu <notifications@github.com>
wrote:

> Yes @djinn <https://github.com/djinn> I saw that and have also run on
> v1.5 so I suggest that we only run for stable versions of go, let's run
> only for 1.4 and 1.5. Do you want to make this change in .travis.yml? Would
> be nice if we do this first before merging
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vanng822/go-solr/pull/34#issuecomment-167531419>.
>



-- 
Supreet Sethi
Ph US: +19173102635
Ph IN: +919811143517
Code: http://osrc.dfm.io/djinn
Ph Skype: d_j_i_n_n
Profile: http://www.google.com/profiles/supreet.sethi
Twt: http://twitter.com/djinn

**Comment by vanng822** [comment]
Look like didn't help but the output is ok. I merge and rewrite the tests to use regexp instead

Thank you for your help!

**Pull request merged**
